ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

ifndef IOPKT_MK
IOPKT_MK= ../../../../../io-pkt.mk
endif
-include $(IOPKT_MK)

ifndef IOPKT_ROOT
IOPKT_ROOT:=../../../../../io-pkt
endif

include ../../../prodroot_pkt.mk
include tgt.mk

EXTRA_INCVPATH+= $(IOPKT_ROOT)/sys $(IOPKT_ROOT)/sys/sys-nto $(IOPKT_ROOT)/lib/socket/public

LIBS = netdrvrS cacheS

NAME = devnp-$(PROJECT)

#treat warning as error
CCFLAGS+=	-Werror

define PINFO
PINFO DESCRIPTION=dm814x ethernet driver
endef


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

