ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk
-include $(PROJECT_ROOT)/roots.mk

define PINFO
PINFO DESCRIPTION=OMAP35xx I2C Driver
endef

ifeq ($(VARIANT2),omap4)
USEMSG = Usemsg-omap4
else
USEMSG = Usemsg
endif

NAME := i2c-$(NAME)
USEFILE = $(PROJECT_ROOT)/$(USEMSG)
INSTALLDIR = sbin
LIBS = i2c-master


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

